### ISSUE TITLE
There is no build-tools 33.2.0

### ISSUE THREAD

**Issue by ArcherEmiya05** [mindrunner/docker-android-sdk#103]
Just want you to know that there seems to be no 33.2.0 version of build tools. After running `sdkmanager --list` these are the only installed packages.

<img width="996" alt="image" src="https://github.com/user-attachments/assets/730d43a1-ff12-4b3c-9f5d-1244eabc7651">

This seems to be confirmed after checking [this](https://developer.android.com/tools/releases/build-tools).

**Comment by mindrunner** [comment]
Hmm, must be a typo. Thanks.

Fixed
