### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by sebhaub** [mindrunner/docker-android-sdk#11]
Hi There,

do you maybe know an easy way to include proxy settings for the sdk manager?
It seems like the sdkmanager is ignoring HTTP_PROXY / HTTPS_PROXY environment variables.

thanks for your help

**Comment by mindrunner** [comment]
Did you try http_proxy / https_proxy (lowercase)?

Also, you should be able to do something like:
`sdkmanager --list --verbose --no_https --proxy=http --proxy_host=<proxy_host> --proxy_port=<proxy_port>
`

Does that help?

**Comment by mindrunner** [comment]
No response
