### ISSUE TITLE
Alpine Images?

### ISSUE THREAD

**Issue by khoanguyen96** [mindrunner/docker-android-sdk#12]
Hey, have you considered using alpine images as a base for a smaller image size? I feel especially for the lazydl image it would immensely benefit from the size reduction.

I wouldn't mind spending some time to create additional Dockerfiles for alternative alpine versions.

Thanks for the awesome images!

**Comment by mindrunner** [comment]
Would be cool to see alpine images as well. Feel free to make a PR. :)
