### ISSUE TITLE
Docker exec failed on OOM

### ISSUE THREAD

**Issue by AvivVegh** [mindrunner/docker-android-sdk#15]
Hi,

I was using same image for a while and everything was fine, in the last month it just stop working 

docker exec builder-1513502440463 /bin/sh -c './gradlew clean assembleRelease --configure-on-demand -PversionCode=1 -x test'
Its start downloading gradle:
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip
and fails

**Comment by goforgold** [comment]
@AvivVegh can you please tell what error message you see in the logs?

**Comment by mindrunner** [comment]
@AvivVegh Can you please give more information? Where do you run this build? Which source code? What exactly fails?

**Comment by mindrunner** [comment]
No answer from @AvivVegh
