### ISSUE TITLE
Lazydl:  /opt/android-sdk-linux empty

### ISSUE THREAD

**Issue by mklueh** [mindrunner/docker-android-sdk#16]
It says "The SDK itself will be downloaded into a volume which is persistent and accessible by other conainers as well. I used a separate branch for this.", but my /opt/android-sdk-linux directory is empty.

How is this image meant to be used?

**Comment by mindrunner** [comment]
Indeed, there is a lack of documentation and it might be not really intuitive to use the image in this way. The idea is to have two containers for the build process. One of which is the builing container executing the actual build. The other one is the sdk-data container, which downloads the whole SDK into a named docker volume which is shared between both containers.

I will provide an example docker-compose file to make this more clear. Might take a couple of days, though.

If you provide more information about how you try to use this, I might be able to point you into the right direction to get this working.

**Comment by mindrunner** [comment]
Hi, sorry for the delay! I figured out that it is actually not that easy to give an example which makes things clear. I started doing some work with docker-compose and an example-docker-container in a feature branch. Feel free to have a look or wait until I manage to sort things out.

https://github.com/mindrunner/docker-android-sdk/tree/feature/example-and-locking
