### ISSUE TITLE
Step 10: no such file or directory 

### ISSUE THREAD

**Issue by bartp1990** [mindrunner/docker-android-sdk#17]
I am trying to build the image with docker and I get this error:

Step 10/14 : COPY tools /opt/tools
COPY failed: stat /var/lib/docker/tmp/docker-builder873443861/tools: no such file or directory
I am using ubuntu-standalone and building with a --no-cache flag.

Thank you for creating and maintaining the image!

**Comment by mindrunner** [comment]
You need to build from the repo root directory!

> docker build . -f ubuntu/standalone/Dockerfile

**Comment by bartp1990** [comment]
Thank you! I think I did not completely understand. Sorry.
