### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by j2ghz** [mindrunner/docker-android-sdk#2]
When pulling this image, the last part, made by line `RUN chown -R 1000:1000 $ANDROID_HOME` has 2.73GB (MicroBadger says 2.5GB)
Would the image get smaller if it was removed?

**Comment by mindrunner** [comment]
Quite interesting. Where do you see the layers size? I will try next week in a feature branch to buikd with this line removed. However, I doubt that it will reduce image size a lot.

**Comment by j2ghz** [comment]
When running `docker pull`.

It depend on whether when `chown` changes the files, only the newest version is kept, or both.

**Comment by mindrunner** [comment]
Looks good. Check the feature/no-chown. Size reduced by approx 2.5Gb :)

**Comment by j2ghz** [comment]
Nice 👍
Will it be available in master (latest) as well, or should I use `feature_no-chown`?

**Comment by mindrunner** [comment]
I am going to have a look into the container and test it on my integration CI before merging it into master. I have to make sure, that it will not break things. Might happen next couple of days,

**Comment by mindrunner** [comment]
merged!
