### ISSUE TITLE
uid 1100

### ISSUE THREAD

**Issue by shamil** [mindrunner/docker-android-sdk#24]
Hey what was the motivation for this commit? https://github.com/mindrunner/docker-android-sdk/commit/3b9d1a810fa5d8939b8d167d1e9a13fc84487dc4

This causing permission issues when we run under CI (which uses uid 1000 inside container).

**Comment by shamil** [comment]
We use Jenkins. In Jenkins we run all builds in containers. Jenkins runs containers with the same UID as the Jenkins process. Which is happen to be `1000`.  

With the new image we started to get errors when running `gradle`

Example:

```
Caused by: java.lang.RuntimeException: Failed to install the following SDK components:
[Android SDK Platform 26, Android SDK Build-Tools 26.0.2]
The SDK directory (/opt/android-sdk-linux) is not writeable,
```

**Comment by mindrunner** [comment]
I created a featue branch for going back to UID 1000. This one is built on docker cloud as well. Please use that one until I found a solution

**Comment by mindrunner** [comment]
Master is reverted to UID 1000
