### ISSUE TITLE
Updating Build Tools to 28.0.2

### ISSUE THREAD

**Issue by herbeth1u** [mindrunner/docker-android-sdk#30]
Hey!

The latest version of the SDK Build Tools used in the image is 28.0.0 in `package-list-minimal` and 28.0.0-rc02 in `package-list`. However version 28.0.2 is available since August ( https://developer.android.com/studio/releases/build-tools ).

Is it possible to add it in `package-list` and replace it in `package-list-minimal`?
Thanks!

**Comment by mindrunner** [comment]
https://github.com/mindrunner/docker-android-sdk/pull/33
