### ISSUE TITLE
Licenses not accepted and ndk-bundle

### ISSUE THREAD

**Issue by pfaffenrodt** [mindrunner/docker-android-sdk#31]
Just tried to use image "runmymind/docker-android-sdk:alpine-lazydl" and got some licenses errors.

```
File /opt/android-sdk-linux/.android/repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 27.0.3 in /opt/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 27.0.3 not accepted.
Checking the license for package Android SDK Platform 28 in /opt/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 28 not accepted.
```

I was first using standalone image, because it was recommended to use for pipelines.
"Standalone This is the standard expected behaviour. The Android SDK is integrated in the docker image. Use this in your android build on CircleCI, Bitbucket Pipelines, or any other docker enabled CI."
But "Standalone" is not providing the ndk-bundle, so I switched to the "lazydl" one.
Maybe ndk-bundle could be added to the Standalone?

**Comment by mindrunner** [comment]
About Licenses:
They should be accepted in all of the images. Can you provide more details of how you are using it?

About ndk-bundle:
You should be able to install it with sdkmanager on the fly in standalone image. We can also add it i suppose. Feel free to PR.

**Comment by pfaffenrodt** [comment]
image: runmymind/docker-android-sdk:alpine-lazydl

build:
        minSdkVersion = 23
        targetSdkVersion = 28
        compileSdkVersion = 28
         'com.android.tools.build:gradle:3.1.4

executed:
/gradlew test

**Comment by mindrunner** [comment]
This is a local build?

**Comment by pfaffenrodt** [comment]
No in a CI Build (gitlab runner).

**Comment by mindrunner** [comment]
Do you have license issues with standalone as well?

**Comment by pfaffenrodt** [comment]
I guess not, it failed because of the missing ndk.

It may had been crashed after checking dependencies.
I compared logs of both builds. Both builds failed at the same point.

**Comment by mindrunner** [comment]
So we just added the ndk part. I suppose it will not fail anymore?

**Comment by pfaffenrodt** [comment]
I can  try.

**Comment by pfaffenrodt** [comment]
So I tried a build with "latest" tag. It was earlier in docker hub. 

The build succeeded.

I also tried it with the new alpine-lazydl build and there it is still this issue.

I will stick on "latest" tag.

**Comment by pfaffenrodt** [comment]
You could try to switch target sdk to 28
