### ISSUE TITLE
opt/android-sdk-linux/tools: no such file or directory

### ISSUE THREAD

**Issue by hasbisevinc** [mindrunner/docker-android-sdk#34]
https://github.com/mindrunner/docker-android-sdk/blob/8680e3a927a8108a25378254db7b3e3b54223a49/ubuntu/lazydl/Dockerfile#L39

I get this error on line 39. how can I fix? thank you

error:
Step 11 : COPY /opt/android-sdk-linux/tools /opt/tools
INFO[0000] opt/android-sdk-linux/tools: no such file or directory

**Comment by hasbisevinc** [comment]
running on root fixed my problem
`sudo docker build  -f ubuntu/lazydl/Dockerfile .`

**Comment by mindrunner** [comment]
I wonder why this happens to you as a non-root user. It sounds for me like a local permissions issue. Let me know if you want to dig deeper into this.
