### ISSUE TITLE
Trying to create avd (in bitbucket pipeline) - getting package path not valid

### ISSUE THREAD

**Issue by malcooke** [mindrunner/docker-android-sdk#35]
Hi,

I'm new to docker etc so might be something stupid on my part.

Using the following:
runmymind/docker-android-sdk:ubuntu-standalone

and issuing the following command to build an avd:
echo no | /opt/android-sdk-linux/tools/bin/avdmanager create avd -n test -k "system-images;android-26;google_apis;x86"

getting the following error:
Error: Package path is not valid. Valid system image paths are:
null

I presumed that using the standalone version that all system-images would be present and licenses etc accepted. Is that the  case or is there something more I need to do?

Thanks

Malcolm

**Comment by mindrunner** [comment]
Look here for installed packages in standalone Image:
https://github.com/mindrunner/docker-android-sdk/blob/master/tools/package-list-minimal.txt

You need to install your system image with sdkmanager first.

You can see the result of putting all packages into the SDK Folder by starting the lazydl image. It will take hours depending on your internet connection and will use about 260GB of data on your hard disk...

**Comment by malcooke** [comment]
ok thank you that makes sense. 

One other question please - which directory  is the wait for emulator script installed to?

thanks for a speedy response.

Malcolm

**Comment by malcooke** [comment]
Thanks for your help - all good now :)
