### ISSUE TITLE
Dockerfile ENV

### ISSUE THREAD

**Issue by ycrxun** [mindrunner/docker-android-sdk#5]
ENV PATH ${PATH}:${ANDROID_SDK_HOME}/tools:${ANDROID_SDK_HOSDK_ME}/platform-tools:/opt/tools

to 

ENV PATH ${PATH}:${ANDROID_SDK_HOME}/tools:${ANDROID_SDK_HOME}/platform-tools:/opt/tools

**Comment by mindrunner** [comment]
Pull Request?

**Comment by mindrunner** [comment]
Thanks

**Comment by ycrxun** [comment]
@mindrunner You're welcome :smile:
