### ISSUE TITLE
OpenJDK no longer supports Alpine

### ISSUE THREAD

**Issue by oxr463** [mindrunner/docker-android-sdk#50]
See: https://github.com/docker-library/openjdk/issues/272

**Comment by oxr463** [comment]
I have been running into some Alpine-specific issues on a project, and I was going to try to submit a PR to update the alpine standalone image when I found this.

**Comment by mindrunner** [comment]
There are other alpine issues in this project (#44) which need attention.
Maybe we could stick to the google supported OS Ubuntu (if that did not change, yet) and stop maintaining alpine here.
Or what do you recommend?

**Comment by oxr463** [comment]
>  Maybe we could stick to the google supported OS Ubuntu (if that did not change, yet) and stop maintaining alpine here.

Perhaps that might be best as it would simplify maintenance.

Really unfortunate since I am a package maintainer for Alpine and a really big fan of the project altogether.

**Comment by mindrunner** [comment]
Yes, I really like alpine as well.

But there must be a solution for java+alpine, right?

**Comment by oxr463** [comment]
> But there must be a solution for java+alpine, right?

We could build our own image based on Alpine directly, instead of inheriting from OpenJDK image.

If you are interested in this, I can submit a PR.

**Comment by mindrunner** [comment]
Ah nice. Yes, I am very interested. Happy to merge your PR.
