### ISSUE TITLE
Ineligible Repository for Hacktoberfest

### ISSUE THREAD

**Issue by emartynov** [mindrunner/docker-android-sdk#61]
Up to you :)

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by mindrunner** [comment]
Not sure what that means. Can you elaborate a bit for me please?

**Comment by emartynov** [comment]
https://hacktoberfest.digitalocean.com/details#maintainers

**Comment by emartynov** [comment]
If you mark you repo as part of Hacktoberfest you might get additional attention from contributors.

**Comment by mindrunner** [comment]
Cool, thanks! Done! :)
