### ISSUE TITLE
DeviceException: No connected devices

### ISSUE THREAD

**Issue by NinjaRat84** [mindrunner/docker-android-sdk#64]
Hi,

I'm trying to trigger instrumented tests on a GitLab pipeline

// This part works as intended
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
- echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n test --force -k "system-images;android 30;google_apis;x86_64" --abi google_apis/x86_64
- $ANDROID_HOME/tools/emulator -avd test -no-window -no-audio &
- ./opt/tools/android-wait-for-emulator.sh
-> I receive that emulator is running

// But when I trigger the tests
- ./gradlew connectedDebugAndroidTest

The tests fails due to: DeviceException: No connected devices
It seems like the emulator went missing during the time the tests where built (about 7-8mins)

Is it possible to extend the timeout for the emulator?

Best regards

**Comment by mindrunner** [comment]
I am not aware of any timeouts. Can you provide a reproducible example (best with some code), so that I can have a look into it?

**Comment by NinjaRat84** [comment]
This could be closed, seems to be the same underlying issues as for #44
