### ISSUE TITLE
package-list.txt and package-list-minimal.txt logic swapped?

### ISSUE THREAD

**Issue by wischweh** [mindrunner/docker-android-sdk#70]
On my builds the **lazydl** uses the packages defined in **package-list.txt** 

but the **standalone** flavor uses **package-list-minimal.txt**.

To my understanding of the Readme (and purpose of lazydl) it should be the other way round.

I think 
android-sdk-update.sh.L52 should rather look like this:
`if [ $built_in_sdk -eq 0 ]`

**Comment by mindrunner** [comment]
Even though, this might be  somewhat confusing, I think it makes sense as it is:

As you can see in `README.md`, regular users would probably use the standalone image. There was a commit some years ago changing the default behavior to only include the minimal packages in the standalone image for some reasons:

- most users only need the most recent packages
- the resulting image with the full installation would be very big, thus lowering the build speeds/user experience on CI/CD systems

The `lazy-dl` image was made for a special use case (see README.md) where the image itself loads the complete SDK into a shared volume and maintains/updates it on container start. (This is usually NOT what you want)

------------------------------------------

Are you encountering any issue? Is something missing for you in the `standalone` images? I am sure we can sort it out! :)

**Comment by mindrunner** [comment]
No answer from OP, closing.
