### ISSUE TITLE
Provide support for NDK and Cmake dependencies

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [mindrunner/docker-android-sdk#71]
Since people are publishing to Google Play Store **app bundles**, it would be desired to upload also native debug symbols inside this bundle.
Many libraries may contain native (C++) code - either in-app or via 3rd party library.

Hence, it is desired to provide debug symbols, like in this question: https://stackoverflow.com/questions/63373245/how-to-add-debug-symbols-to-build-gradle

Could you please create an android image with NDK setup?

**Comment by mindrunner** [comment]
AFAIK, this is already implemented. If you face any issues, please provide a proper reproducible example! 

Thanks

**Comment by mindrunner** [comment]
No answer from OP, closing.
