### ISSUE TITLE
Does it support sdk android-31

### ISSUE THREAD

**Issue by psaini0212** [mindrunner/docker-android-sdk#81]
Hi, I am new to this. does this support android-31? The highest I can see under https://github.com/mindrunner/docker-android-sdk/blob/master/tools/package-list.txt is android-30. Please can you confirm

**Comment by mindrunner** [comment]
Seems like Android 31 has not been added yet. Feel free to create a PR. Cheers

**Comment by brandonros** [comment]
Check out https://github.com/alvr/alpine-android which has Android 31, 32, 33 if needed

**Comment by mindrunner** [comment]
As already said, it just has to be added. Feel free to open a PR :)
