### ISSUE TITLE
Missing SDK 32 and 33

### ISSUE THREAD

**Issue by ArcherEmiya05** [mindrunner/docker-android-sdk#95]
Hi, is there a plan to include SDK 32, 33 and possibly 34? These version is nowhere to be found in Docker Hub. Thanks

**Comment by mindrunner** [comment]
`32` and `33` should be included. Do you face any issues?

`34` just added as of https://github.com/mindrunner/docker-android-sdk/commit/4963df1cb6d1a1edf6f08c56377ca27a1fd2031f

Please let me know if that works for you

**Comment by ArcherEmiya05** [comment]
> `32` and `33` should be included. Do you face any issues?
> 
> `34` just added as of [4963df1](https://github.com/mindrunner/docker-android-sdk/commit/4963df1cb6d1a1edf6f08c56377ca27a1fd2031f)
> 
> Please let me know if that works for you

Just wanna know why these version are not showing in Docker Hub, and is the README.md really incomplete or I am looking at a wrong branch?

**Comment by mindrunner** [comment]
> Just wanna know why these versions are not showing in Docker Hub

Not sure If I understand the question. What do you expect to find in docker-hub? If you use the `latest` tag and cannot find the above mentioned versions in the image, please open a new ticket.

> and is the README.md really incomplete 

What is missing in Readme?

**Comment by ArcherEmiya05** [comment]
Hi, there's a lot of TBD including the usage section in README.md. Also I am referring to [this](https://hub.docker.com/r/androidsdk/) docker hub profile.

**Comment by mindrunner** [comment]
> Hi, there's a lot of TBD including the usage section

You are right. I am not rally actively maintaining this anymore. I haven't been developing for Android for years. But I know, many people use my images, hence I keep it up and running, accepting PRs and answering Questions. Feel free to contribute to the Readme if you have something to add.

> [this](https://hub.docker.com/r/androidsdk/) docker hub profile.

Not related to me. Check this out: https://hub.docker.com/r/runmymind/docker-android-sdk
