### ISSUE TITLE
CI builds are hanging after finishing build script

### ISSUE THREAD

**Issue by Kisty** [mindrunner/docker-android-sdk#97]
First off, thanks for this project. It's super helpful!

On Bitbucket Pipelines CI, we're running on a 8g RAM instance and although CI build passes, Bitbucket keeps the container up to the maximum of 2hrs, which they bill us for. No CI builds succeed unfortunately. I've contacted Bitbucket Pipelines support and they've recommended me to run the container on my machine locally using these instructions: https://confluence.atlassian.com/bbkb/troubleshoot-failed-bitbucket-pipelines-locally-with-docker-1318882094.html

![2023-11-30 14 45 51 bitbucket org 9fd8ffc3f812](https://github.com/mindrunner/docker-android-sdk/assets/3243752/52b37fff-8f5d-4fce-b1bc-e6acb4027ba9)
![2023-11-30 14 43 45 bitbucket org 3a582744af7a](https://github.com/mindrunner/docker-android-sdk/assets/3243752/a40b2101-36bf-4dc5-ac32-71cbbff3c0b3)

Nothing has changed except the container version. I've attached the pipeline log. Can you help? Might it be as a result of #92?

app target SDK: 33
app compile SDK: 33
docker-android-sdk: http://docker.io/runmymind/docker-android-sdk@sha256:5e1bb68849a1afa6500cdda394b58726fe71ef261bceb4d8a617e13164bfb280

[pipelineLog-{c8f08f51-cfa9-48e5-8913-612e8694b54d}.txt](https://github.com/mindrunner/docker-android-sdk/files/13636768/pipelineLog-.c8f08f51-cfa9-48e5-8913-612e8694b54d.txt)

For reference, here's the last succeeding build:
![image](https://github.com/mindrunner/docker-android-sdk/assets/3243752/13b717fb-aa0c-4566-80a1-1257dace62a2)
![image](https://github.com/mindrunner/docker-android-sdk/assets/3243752/fec39db2-8d80-420e-a06b-19b1ae18ee1e)
[pipelineLog-{1d462200-35fc-4416-8089-68b81b20be5d}.txt](https://github.com/mindrunner/docker-android-sdk/files/13636905/pipelineLog-.1d462200-35fc-4416-8089-68b81b20be5d.txt)

**Comment by mindrunner** [comment]
Hi, thanks for the detailed report. Can you give me a minimal reproducible example? Maybe link to project and build instructions, such that I can investigate? Can also hop on a call and/or debug directly on your infra if you are interested.

**Comment by Kisty** [comment]
Hi thanks for your help. Looks like 8GB doesn't cut it for the Android build. Am in conversation with BitBucket and changed docker service to take 512MB instead of 1GB so will close issue for now. Thanks!
