### ISSUE TITLE
alpine-standalone crashes from 20231209

### ISSUE THREAD

**Issue by vulpeszerda** [mindrunner/docker-android-sdk#98]
Thank you for your efforts.

I used `runmymind/docker-android-sdk:alpine-standalone` for CI, but it crashes since `runmymind/docker-android-sdk:alpine-standalone-20231209` with error message `AAPT2 aapt2-8.1.4-10154469-linux Daemon #1: Daemon startup failed`

```
#15 [builder 7/8] RUN ./gradlew -Dorg.gradle.jvmargs=-Xmx32g -Dorg.gradle.daemon=false :app:buildAlphaDebug testAlphaDebugUnitTest --stacktrace

...
...

#15 270.1 
#15 270.1 > Task :library:annotation:compileDebugKotlin
#15 270.1 w: Opt-in requirement marker kotlinx.coroutines.FlowPreview is unresolved. Please make sure it's present in the module dependencies
#15 270.1 w: Opt-in requirement marker com.airbnb.mvrx.ExperimentalMavericksApi is unresolved. Please make sure it's present in the module dependencies
#15 282.7 
#15 282.7 > Task :app:l8DexDesugarLibAlphaDebug
#15 290.1 > Task :app:mergeExtDexAlphaDebug
#15 332.3 
#15 332.3 FAILURE: Build completed with 2 failures.
#15 332.3 
#15 332.3 1: Task failed with an exception.
#15 332.3 -----------
#15 332.3 * What went wrong:
#15 332.3 Execution failed for task ':app:processAlphaDebugResources'.
#15 332.3 > Could not resolve all files for configuration ':app:alphaDebugRuntimeClasspath'.
#15 332.3    > Failed to transform mavericks-launcher-3.0.7.aar (com.airbnb.android:mavericks-launcher:3.0.7) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
#15 332.3       > Execution failed for AarResourcesCompilerTransform: /root/.gradle/caches/transforms-3/ff62b48c7a8c589ebc800bb99a7377dc/transformed/mavericks-launcher-3.0.7.
#15 332.3          > AAPT2 aapt2-8.1.4-10154469-linux Daemon #1: Daemon startup failed
#15 332.3            This should not happen under normal circumstances, please file an issue if it does.
#15 332.3    > Failed to transform chatlib-1.0.3-SNAPSHOT.aar (com.kakaomobility.chatlib:chatlib:1.0.3-SNAPSHOT:20231205.054134-2) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=integration, org.gradle.usage=java-runtime}.
#15 332.3       > Execution failed for AarResourcesCompilerTransform: /root/.gradle/caches/transforms-3/186fc426fef40b884d5fa60be827aaa3/transformed/chatlib-1.0.3-SNAPSHOT.
#15 332.3          > AAPT2 aapt2-8.1.4-10154469-linux Daemon #0: Daemon startup failed
#15 332.3            This should not happen under normal circumstances, please file an issue if it does.
#15 332.3    > Failed to transform knsdk_ui-1.9.1.aar (com.kakaomobility.knsdk:knsdk_ui:1.9.1) to match attributes 
```

I suppose there were some changes in base alpine linux image because [alpine-standalone-20231208](https://hub.docker.com/layers/runmymind/docker-android-sdk/alpine-standalone-20231208/images/sha256-c908376f4e770bb4b52cd1cdc8fd0ad26468da3a588600afa6c61173fda05b1c?context=explore) and [alpine-standalone-20231209](https://hub.docker.com/layers/runmymind/docker-android-sdk/alpine-standalone-20231209/images/sha256-43f61c2a49f89fd46da15fe758d48c59bfa9e0db601942f55ce0e55e01c50438?context=explore) has a difference in base image file hash.

#### alpine-standalone-20231208
`ADD file:1f4eb46669b5b6275af19eb7471a6899a61c276aa7d925b8ae99310b14b75b92 in / `

#### alpine-standalone-20231209
`ADD file:fc714080c3bcbbce7ac746a10d7b4355ffa36293a8d435d62cd5359ea8eb8364 in / `

I changed my Dockerfile to use `alpine-standalone-20231208` instead of `alpine-standalone` and it works fine. 
However I hope this issue to be resolved for receveing continuous docker image update.

Again, thank you for your efforts for maintaining awesome docker image for android 🙂

**Comment by MairwunNx** [comment]
The same issue +1

**Comment by mindrunner** [comment]
This is probably related to Alpine `3.19.0` update. Can you please try with the ubuntu flavour and see if that solves your issue?

**Comment by vulpeszerda** [comment]
@mindrunner ubuntu works fine. I tested with `runmymind/docker-android-sdk:ubuntu-standalone`

**Comment by mindrunner** [comment]
Cool, I'd recommend using `ubuntu`. `alpine` is considered being experimental and is not officially supported. Mileage varies. I might not have time to investigate and fix things, so I guess either someone figures out (PRs welcome) or I sunset alpine images at some point next year. We will see.
