### ISSUE TITLE
Does the latest tag means latest Android SDK as well?

### ISSUE THREAD

**Issue by ArcherEmiya05** [mindrunner/docker-android-sdk#99]
If I use `runmymind/docker-android-sdk:latest` image, will it be always point to the latest Android SDK? 

If yes, does it only use the stable which is API 34 since API 35 is still in beta? 

If the mentioned image uses Ubuntu, is there a version of it that has `zip` command tool? I need to perform archiving build files and upload it. Thanks!

**Comment by mindrunner** [comment]
> If I use runmymind/docker-android-sdk:latest image, will it be always point to the latest Android SDK?

It will point to the latest build of this image. Images are built on a nightly base.

> If yes, does it only use the stable which is API 34 since API 35 is still in beta?

Currently, it contains `32`, `33`, `34` by default. You can always check here:
https://github.com/mindrunner/docker-android-sdk/blob/main/tools/package-list.txt

> Another question is if this tag uses Ubuntu by default, does it come with cURL? 

```
root@27c9cd44b35d:/opt/android-sdk-linux# which curl
/usr/bin/curl
```

> If the mentioned image uses Ubuntu, is there a version of it that has zip command tool?

`zip` is currently not installed, but we can easily add this.

**Comment by mindrunner** [comment]
https://github.com/mindrunner/docker-android-sdk/commit/4ef871bb69cf6215f91ad51cc9fb80365406eb71
